server:
  port: 8081
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # auto schema management
    show-sql: true       # show SQL in logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      
  application:
    name: user-service